### ISSUE TITLE
TurboReflex::InvalidTokenError: CSRF token mismatch

### ISSUE THREAD

**Issue by drnic** [hopsoft/turbo_reflex#47]
Is there something I need to setup/configure to avoid CSRD token mismatch errors?

```
web    | Error in LiveBallReflex#enable_editor! #<TurboReflex::InvalidTokenError: CSRF token mismatch! The request header `TurboReflex-Token: BAhJIhVkdU1td092UzRRVk9mSWZGBjoGRUY=--5f5b4db12e99a26fe3673947127b701f18d4677afeba09cd1dea1f5e2148f228` does not match the expected value of `1J9l8g8QvBAB1uGT`.> ["/Users/drnic/Projects/mylocalcricket/turbo_reflex/lib/turbo_reflex/runner.rb:50:in `reflex_valid?'", "/Users/drnic/Projects/mylocalcricket/turbo_reflex/lib/turbo_reflex/runner.rb:118:in `run'", "/Users/drnic/Projects/mylocalcricket/turbo_reflex/lib/turbo_reflex/controller_pack.rb:14:in `run'", "/Users/drnic/Projects/mylocalcricket/turbo_reflex/app/controllers/concerns/turbo_reflex/controller.rb:13:in `block (2 levels) in <module:Controller>'"]
web    | Filter chain halted as #<Proc:0x00000001139c7048 /Users/drnic/Projects/mylocalcricket/turbo_reflex/app/controllers/concerns/turbo_reflex/controller.rb:13 (lambda)> rendered or redirected
```

My `.html.erb` looks approximately like the README:

```html
<%= turbo_frame_tag dom_id(cricket_ball) do %>
          <a href="#" data-turbo-reflex="LiveBallReflex#enable_editor" class="edit-control">edit</a>
```

and

```ruby
class LiveBallReflex < TurboReflex::Base
  def enable_editor
    puts "enable_editor"
  end
end
```

Oddly, I thought this worked once or two.

I don't know what I did after that - perhaps restarted the server or changed something - but since then I've gotten CSRF token mismatch errors.

**Comment by drnic** [comment]
I can't reproduce the error in another app. Nor have I yet figured out how to make the error go away in this app lol.

**Comment by drnic** [comment]
I must know how computers work anymore. I've tried clearing my cookies, (and other things that aren't relevant but you do them when nothing works, like rebuilding your database, flushing redis), and using a new incognito session, and still getting this error. I shall look at this with fresh eyes another day.

**Comment by hopsoft** [comment]
You'll most likely want to have the token working in a production app, but you can bypass the token validation to help you get around this over the short term. SEE: https://github.com/hopsoft/turbo_reflex/blob/main/test/dummy/config/initializers/turbo_reflex.rb#L24
